### PR TITLE
fix(player): disable shortcuts when adding comment

### LINKED ISSUE #1057: Player keyboard shortcuts triggering outside of focus
https://www.loom.com/share/0fbece3d7e8d4ea09a995dfe1efe72b8

Space key input in comment text area pauses/plays video instead of adding space character. The "f" key is also triggering full-screen.   

Issued discovered when trying to comment on this lesson https://egghead.io/lessons/tailwind-setup-next-js-with-tailwind-in-a-nx-workspace

Reproduced on Brave, Chrome, and Safari.

### PR DESCRIPTION
**Pull request by vojtaholik**
- fixes #1057

gif

### CODE REVIEW

File: src/components/pages/lessons/comments/comment-field/index.tsx [hunk 1]
```diff
@@ -33,7 +41,12 @@ const CommentField: FunctionComponent<CommentFieldProps> = ({
             } = props
             return (
               <div className="max-w-2xl">
-                <form onSubmit={handleSubmit} className="w-full space-y-2">
+                <form
+                  onSubmit={handleSubmit}
+                  className="w-full space-y-2"
+                  onFocusCapture={toggleShortcutsEnabled}
```
Comment (vojtaholik) [inline src/components/pages/lessons/comments/comment-field/index.tsx:47]: we want to fire this event in the capture phase, hence the Capture appendix

**Review by joelhooks — APPROVED** [review]
i changed the title to “fix” (i had to look it up i was using bug too)

**Comment by vojtaholik** [comment]
this isn't working as expected and 1. shortcuts are still triggering when the video is in loading state; 2. initial focus doesn't disable the shortcuts.
